using System.Reflection;


[assembly: AssemblyTitle("Editor.Extension.Editor")]
[assembly: AssemblyDescription("Generated by PackageGenerator.")]
[assembly: AssemblyCompany("rokid")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]